// Cross-language SORT-PARITY test (Milestone 7 of the interactive-bases feature).
//
// The committed `fixtures/sort-*.json` are generated by the Rust engine
// (`crates/docgen-bases/tests/sort_parity.rs`): each pins a v1 payload plus
// `rustOrder` — the id sequence Rust's `Value::loose_cmp` / `render.rs::apply_sort`
// produced for a given sort config over an ADVERSARIAL corpus.
//
// This test proves the JS island reproduces that arrangement INDEPENDENTLY: for
// each fixture we take `payload.rows`, scramble them to a canonical unsorted order
// (sort by id ascending), build `rowsById`, run the island's own
// `sortIds(scrambledIds, rowsById, keys)`, and assert the resulting id sequence
// EQUALS `rustOrder`. A disagreement is a real comparator-parity bug in
// `compareCells`/`sortIds` (or a Rust-side change that wasn't re-blessed).
//
// RUN (from repo root):
//   node --test crates/docgen-assets/js-tests/

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { readFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const require = createRequire(import.meta.url);
const B = require('../assets/docgen/islands/bases.js');

const here = dirname(fileURLToPath(import.meta.url));
const fixturesDir = join(here, 'fixtures');

const fixtureFiles = readdirSync(fixturesDir)
  .filter((f) => /^sort-\d+\.json$/.test(f))
  .sort();

// Guard: the Rust generator must have produced fixtures. An empty directory means
// the harness was never blessed — fail loudly rather than pass vacuously.
test('sort-parity fixtures exist', () => {
  assert.ok(
    fixtureFiles.length > 0,
    'no fixtures/sort-*.json found — run `BLESS=1 cargo test -p docgen-bases --test sort_parity`'
  );
});

for (const file of fixtureFiles) {
  test(`sort parity: ${file}`, () => {
    const fx = JSON.parse(readFileSync(join(fixturesDir, file), 'utf8'));
    const rows = fx.payload.rows;

    // Canonical unsorted order: sort row ids ascending, independent of however
    // Rust happened to arrange the payload. rowsById maps id -> {id, cells}.
    const rowsById = {};
    for (const r of rows) rowsById[r.id] = r;
    const scrambled = rows.map((r) => r.id).sort((a, b) => a - b);

    // Run the island's pure comparator/sort exactly as the browser does.
    const got = B.sortIds(scrambled, rowsById, fx.keys);

    assert.deepEqual(
      got,
      fx.rustOrder,
      `JS sortIds disagreed with Rust for keys ${JSON.stringify(fx.keys)}\n` +
        `  Rust order: ${JSON.stringify(fx.rustOrder)}\n` +
        `  JS   order: ${JSON.stringify(got)}`
    );
  });
}
